#!/usr/bin/env python

from script.main import main_exec
from script.basic_func import logo

print("\n")
print('-------------------')
print('Pocket to Concavity')
print('P2C Ver. 1.1.1 ')
print('-------------------\n')

if __name__ == '__main__':
    logo()
    main_exec()
print('-------------------')
print('   P2C finished    ')
print('-------------------')

