#!/usr/bin/env python

from script.main import main_exec

print('--------Pocket to Concavity--------')
print('               (P2C)               ')
print('')

if __name__ == '__main__':
    outdir = "p2c_output"
    main_exec(outdir)
print('')
print('----------P2C terminated-----------')

